 <div><center><img src="https://upload.wikimedia.org/wikipedia/fr/9/99/Logo_Polytechnique_Montr%C3%A9al.png"
width="300"/></div>

#    <center> GCH3515 Phénomènes d'échange — Exemple 01
### <center> **Antony Gareau-Lajoie, CPI - Auxiliaire d'enseignement**
### <center> Département de génie chimique
### <center> Polytechnique Montréal


In [1]:
# INSTALLATION
%pip install -q ipywidgets
%pip install -q pint
%pip install -q plotly
%pip install -q chart_studio

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
# IMPORTATION DES LIBRAIRIES
import numpy as np
import pint
import plotly.graph_objects as go
import plotly.io as pio
from ipywidgets import interactive
import chart_studio.plotly as py


# CONFIGURATION
pio.templates.default = "plotly_white"
u = pint.UnitRegistry()

In [3]:
# DICTIONNAIRE DES CONSTANTES DU PROBLÈME
dico = {
    "t":1.0   *  u.hour,
    "v":200.0 * (u.m/u.minute),
        }
print(dico)

{'t': <Quantity(1.0, 'hour')>, 'v': <Quantity(200.0, 'meter / minute')>}


In [4]:
# EXEMPLE D'AFFICHAGE
temps, vitesse = dico["t"], dico["v"]
print(
    """
    En {:.3g} minutes et
    en allant à une vitesse de {:.3g} mètres par secondes,
    j'ai parcouru {:.1f} kilomètres.
    """.format(temps.to(u.minute).magnitude,
               vitesse.to_base_units().magnitude,
               (temps*vitesse).to(u.km).magnitude))


    En 60 minutes et
    en allant à une vitesse de 3.33 mètres par secondes,
    j'ai parcouru 12.0 kilomètres.
    


In [5]:
# RÉSOLUTION SYMBOLIQUE

In [6]:
# RÉSOLUTION NUMÉRIQUE

In [7]:
# PRÉPARATION POUR VISUALISATION
def f(x, y):
    return 2*x + y**2

x_vecteur = [1, 2, 3, 4, 5]
y_vecteur = [1, 2, 3, 4, 5]
z_matrice = np.empty((0, len(y_vecteur)))
for x in x_vecteur :
    z_liste = []
    for y in y_vecteur :
        z_liste.append(f(x,y))
    z_matrice = np.append(z_matrice,np.array([z_liste]),axis=0)

print(z_matrice)

[[ 3.  6. 11. 18. 27.]
 [ 5.  8. 13. 20. 29.]
 [ 7. 10. 15. 22. 31.]
 [ 9. 12. 17. 24. 33.]
 [11. 14. 19. 26. 35.]]


In [8]:
# VISUALISATION
fig = go.Figure(data = go.Contour(x=x_vecteur, y=y_vecteur, z=z_matrice))

fig.update_layout(dict(title=dict(text="Visualisation en courbes de niveaux",
                                  font_size=20),

                       xaxis=dict(title="x2 [-]",
                                  titlefont_size=16,
                                  linecolor="black",
                                  showline=True,
                                  mirror=True,
                                  linewidth=1,
                                  gridcolor='darkgray',
                                  gridwidth=1,
                                  zeroline=False
                                 ),

                       yaxis=dict(title="x1 [-]",
                                  titlefont_size=16,
                                  linecolor="black",
                                  showline=True,
                                  mirror=True,
                                  linewidth=1,
                                  gridcolor='darkgray',
                                  gridwidth=1,
                                  zeroline=False
                                  ),

                       coloraxis=dict(colorbar_title_text="x3"),

                       width=700,
                       height=500,
))

fig.show()

In [10]:
# VISUALISATION INTERACTIVE
def graphique_interactif(c1, c2):

    def f(x, y, c1, c2):
        return c1*x + y**c2

    x_vecteur = [1, 2, 3, 4, 5] 
    y_vecteur = [1, 2, 3, 4, 5]  
    z_matrice = np.empty((0, len(y_vecteur)))
    for x in x_vecteur :
        z_liste = []
        for y in y_vecteur :
            z_liste.append(f(x, y, c1, c2))
        z_matrice = np.append(z_matrice,np.array([z_liste]),axis=0)

    # VISUALISATION
    fig = go.Figure(data = go.Contour(x=x_vecteur, y=y_vecteur, z=z_matrice))

    fig.update_layout(dict(title=dict(text="Visualisation en courbes de niveaux",
                                    font_size=20),

                        xaxis=dict(title="x2 [-]",
                                    titlefont_size=16,
                                    linecolor="black",
                                    showline=True,
                                    mirror=True,
                                    linewidth=1,
                                    gridcolor='darkgray',
                                    gridwidth=1,
                                    zeroline=False
                                    ),

                        yaxis=dict(title="x1 [-]",
                                    titlefont_size=16,
                                    linecolor="black",
                                    showline=True,
                                    mirror=True,
                                    linewidth=1,
                                    gridcolor='darkgray',
                                    gridwidth=1,
                                    zeroline=False
                                    ),

                        coloraxis=dict(colorbar_title_text="x3"),

                        width=700,
                        height=500,
    ))

    py.iplot(fig, filename='jupyter-parametric_plot')


    #fig.show()

interactive_plot = interactive(graphique_interactif, c1=(-2.0, 2.0, 0.5), c2=(-3, 3, 0.5))
output = interactive_plot.children[-1]
output.layout.height = '200px'
interactive_plot


interactive(children=(FloatSlider(value=0.0, description='c1', max=2.0, min=-2.0, step=0.5), FloatSlider(value…